-- Leaders_AI
-- Author: wldcmzy
-- DateCreated: 3/3/2024 4:40:19 PM
--------------------------------------------------------------


INSERT INTO AiListTypes
-- LEADER_STELLARIS_WITCH_6
-------------------------------------------------------------------------------------------------

-- LEADER_STELLARIS_ELLIS_5
-------------------------------------------------------------------------------------------------


-- LEADER_STELLARIS_ZOEY_3
-------------------------------------------------------------------------------------------------



-- LEADER_STELLARIS_GREY
-------------------------------------------------------------------------------------------------
(	ListType) VALUES
(	'LEADER_STELLARIS_WITCH_6_Diplo'),
(	'LEADER_STELLARIS_WITCH_6_Ally'),
(	'LEADER_STELLARIS_WITCH_6_PlotEv'),
(	'LEADER_STELLARIS_WITCH_6_Strategies'),
(	'LEADER_STELLARIS_WITCH_6_Yields'),
(	'LEADER_STELLARIS_WITCH_6_PsYields'),
(	'LEADER_STELLARIS_WITCH_6_Techs'),
(	'LEADER_STELLARIS_WITCH_6_Districts'),
(	'LEADER_STELLARIS_WITCH_6_Buildings'),
(	'LEADER_STELLARIS_WITCH_6_Units'),
(	'LEADER_STELLARIS_WITCH_6_Proj'),
(	'LEADER_STELLARIS_ELLIS_5_Diplo'),
(	'LEADER_STELLARIS_ELLIS_5_Ally'),
(	'LEADER_STELLARIS_ELLIS_5_PlotEv'),
(	'LEADER_STELLARIS_ELLIS_5_Strategies'),
(	'LEADER_STELLARIS_ELLIS_5_Yields'),
(	'LEADER_STELLARIS_ELLIS_5_PsYields'),
(	'LEADER_STELLARIS_ELLIS_5_Techs'),
(	'LEADER_STELLARIS_ELLIS_5_Civics'),
(	'LEADER_STELLARIS_ELLIS_5_Districts'),
(	'LEADER_STELLARIS_ELLIS_5_Buildings'),
(	'LEADER_STELLARIS_ELLIS_5_Units'),
(	'LEADER_STELLARIS_ELLIS_5_Proj'),
(	'LEADER_STELLARIS_ZOEY_3_Diplo'),
(	'LEADER_STELLARIS_ZOEY_3_Ally'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv'),
(	'LEADER_STELLARIS_ZOEY_3_Strategies'),
(	'LEADER_STELLARIS_ZOEY_3_Yields'),
(	'LEADER_STELLARIS_ZOEY_3_PsYields'),
(	'LEADER_STELLARIS_ZOEY_3_Techs'),
(	'LEADER_STELLARIS_ZOEY_3_Districts'),
(	'LEADER_STELLARIS_ZOEY_3_Buildings'),
(	'LEADER_STELLARIS_ZOEY_3_Proj'),
(	'LEADER_STELLARIS_GREY_Diplo'),
(	'LEADER_STELLARIS_GREY_Ally'),
(	'LEADER_STELLARIS_GREY_PlotEv'),
(	'LEADER_STELLARIS_GREY_Strategies'),
(	'LEADER_STELLARIS_GREY_Yields'),
(	'LEADER_STELLARIS_GREY_PsYields'),
(	'LEADER_STELLARIS_GREY_Techs'),
(	'LEADER_STELLARIS_GREY_Civics'),
(	'LEADER_STELLARIS_GREY_Districts'),
(	'LEADER_STELLARIS_GREY_Buildings'),
(	'LEADER_STELLARIS_GREY_Proj');

INSERT INTO AiLists
-- LEADER_STELLARIS_WITCH_6
-------------------------------------------------------------------------------------------------


-- LEADER_STELLARIS_ELLIS_5
-------------------------------------------------------------------------------------------------



-- LEADER_STELLARIS_ZOEY_3
-------------------------------------------------------------------------------------------------



-- LEADER_STELLARIS_GREY
-------------------------------------------------------------------------------------------------
(	LeaderType,							ListType,									System) VALUES
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Diplo',			'DiplomaticActions'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Ally',			'Alliances'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_PlotEv',			'PlotEvaluations'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Strategies',		'Strategies'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Yields',			'Yields'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_PsYields',		'PseudoYields'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Techs',			'Techs'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Districts',		'Districts'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Buildings',		'Buildings'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Units',			'Units'),
(	'TRAIT_LEADER_STELLARIS_WITCH_6',	'LEADER_STELLARIS_WITCH_6_Proj',			'Projects'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DiplomaticActions'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Ally',			'Alliances'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_PlotEv',			'PlotEvaluations'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Strategies',		'Strategies'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Yields',			'Yields'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_PsYields',		'PseudoYields'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Techs',			'Techs'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Civics',			'Civics'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Districts',		'Districts'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Buildings',		'Buildings'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Units',			'Units'),
(	'TRAIT_LEADER_STELLARIS_ELLIS_5',	'LEADER_STELLARIS_ELLIS_5_Proj',			'Projects'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DiplomaticActions'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_Ally',				'Alliances'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'PlotEvaluations'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_Strategies',		'Strategies'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_Yields',			'Yields'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_PsYields',			'PseudoYields'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_Techs',			'Techs'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_Districts',		'Districts'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_Buildings',		'Buildings'),
(	'TRAIT_LEADER_STELLARIS_ZOEY_3',	'LEADER_STELLARIS_ZOEY_3_Proj',				'Projects'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Diplo',				'DiplomaticActions'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Ally',				'Alliances'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_PlotEv',				'PlotEvaluations'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Strategies',			'Strategies'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Yields',				'Yields'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_PsYields',			'PseudoYields'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Techs',				'Techs'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Civics',				'Civics'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Districts',			'Districts'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Buildings',			'Buildings'),
(	'TRAIT_LEADER_STELLARIS_GREY',		'LEADER_STELLARIS_GREY_Proj',				'Projects');

INSERT INTO AiFavoredItems
-- LEADER_STELLARIS_WITCH_6
-------------------------------------------------------------------------------------------------








--('LEADER_STELLARIS_WITCH_6_Techs',		'TECH_IRON_WORKING',						1,		0,	NULL),
--('LEADER_STELLARIS_WITCH_6_Techs',		'TECH_APPRENTICESHIP',						1,		0,	NULL),

--('LEADER_STELLARIS_WITCH_6_Districts',	'DISTRICT_HOLY_SITE',						0,		0,	NULL),









-- LEADER_STELLARIS_ELLIS_5
-------------------------------------------------------------------------------------------------



















-- LEADER_STELLARIS_ZOEY_3
-------------------------------------------------------------------------------------------------






--('LEADER_STELLARIS_ZOEY_3_PlotEv',		'New Resources',							1,		0,		NULL),












-- LEADER_STELLARIS_GREY
-------------------------------------------------------------------------------------------------












(	ListType,									Item,										Favored,	Value,		StringVal) VALUES
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_OPEN_BORDERS',					0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_MAKE_PEACE',					0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DIPLOMATIC_DELEGATION',		0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_RESIDENT_EMBASSY',				0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_FRIENDSHIP',			0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_COLONIAL_WAR',			1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_GOLDEN_AGE_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_IDEOLOGICAL_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_WAR_OF_RETRIBUTION',	1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_THIRD_PARTY_WAR',				1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_FORMAL_WAR',			1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_HOLY_WAR',				1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_LIBERATION_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_PROTECTORATE_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_RECONQUEST_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_SURPRISE_WAR',			1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_TERRITORIAL_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DECLARE_WAR_MINOR_CIV',		1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_DENOUNCE',						1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_JOINT_WAR',					1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_USE_NUCLEAR_WEAPON',			1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_ALLIANCE',						0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_ALLIANCE_CULTURAL',			0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_ALLIANCE_ECONOMIC',			0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_ALLIANCE_RESEARCH',			0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_ALLIANCE_MILITARY',			0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Diplo',			'DIPLOACTION_ALLIANCE_RELIGIOUS',			0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Ally',			'ALLIANCE_CULTURAL',						0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Ally',			'ALLIANCE_ECONOMIC',						0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Ally',			'ALLIANCE_RESEARCH',						0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Ally',			'ALLIANCE_MILITARY',						0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Ally',			'ALLIANCE_RELIGIOUS',						0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PlotEv',			'TotalYield',								1,			8,			'YIELD_PRODUCTION'),
(	'LEADER_STELLARIS_WITCH_6_PlotEv',			'SpecificResource',							1,			6,			'RESOURCE_HORSES'),
(	'LEADER_STELLARIS_WITCH_6_PlotEv',			'SpecificResource',							1,			6,			'RESOURCE_IRON'),
(	'LEADER_STELLARIS_WITCH_6_PlotEv',			'SpecificResource',							1,			3,			'RESOURCE_NITER'),
(	'LEADER_STELLARIS_WITCH_6_PlotEv',			'SpecificResource',							1,			2,			'RESOURCE_COAL'),
(	'LEADER_STELLARIS_WITCH_6_PlotEv',			'SpecificResource',							1,			12,			'RESOURCE_OIL'),
(	'LEADER_STELLARIS_WITCH_6_PlotEv',			'SpecificResource',							1,			8,			'RESOURCE_URANIUM'),
(	'LEADER_STELLARIS_WITCH_6_Strategies',		'VICTORY_STRATEGY_MILITARY_VICTORY',		1,			-4,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Yields',			'YIELD_PRODUCTION',							1,			20,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Yields',			'YIELD_SCIENCE',							1,			5,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_DIPLOMATIC_FAVOR',				1,			-100,		NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_WONDER',						0,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_UNIT_COMBAT',					1,			50,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_UNIT_NAVAL_COMBAT',			1,			15,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_UNIT_AIR_COMBAT',				1,			25,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_CITY_BASE',					1,			40,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_CITY_DEFENDING_UNITS',			1,			-10,		NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_CITY_DEFENSES',				1,			-10,		NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_GPP_ADMIRAL',					1,			10,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_GPP_GENERAL',					1,			55,			NULL),
(	'LEADER_STELLARIS_WITCH_6_PsYields',		'PSEUDOYIELD_NUCLEAR_WEAPON',				1,			50,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Techs',			'TECH_NUCLEAR_FUSION',						1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Techs',			'TECH_NUCLEAR_FISSION',						1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Techs',			'TECH_WRITING',								1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Techs',			'TECH_THE_WHEEL',							1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Techs',			'TECH_HORSEBACK_RIDING',					1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Techs',			'TECH_STIRRUPS',							1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Techs',			'TECH_BRONZE_WORKING',						1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Districts',		'DISTRICT_ENCAMPMENT',						1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Districts',		'DISTRICT_COMMERCIAL_HUB',					1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Buildings',		'BUILDING_TERRACOTTA_ARMY',					1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Buildings',		'BUILDING_OFFSPRING_NEST',					1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Buildings',		'BUILDING_TERRACOTTA_ARMY',					1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Units',			'UNIT_HEAVY_CHARIOT',						1,			2,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Units',			'UNIT_HORSEMAN',							1,			2,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Units',			'UNIT_KNIGHT',								1,			2,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Units',			'UNIT_SWORDSMAN',							1,			2,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Proj',			'PROJECT_BECOME_THE_CRISIS',				1,			0,			NULL),
(	'LEADER_STELLARIS_WITCH_6_Proj',			'PROJECT_LOSSUS_PROJECT',					1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_OPEN_BORDERS',					1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_MAKE_PEACE',					1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DIPLOMATIC_DELEGATION',		1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_RESIDENT_EMBASSY',				1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_FRIENDSHIP',			1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_COLONIAL_WAR',			0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_GOLDEN_AGE_WAR',		0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_IDEOLOGICAL_WAR',		0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_WAR_OF_RETRIBUTION',	1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_THIRD_PARTY_WAR',				0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_LIBERATION_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_PROTECTORATE_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_RECONQUEST_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_SURPRISE_WAR',			0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DECLARE_WAR_MINOR_CIV',		0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_DENOUNCE',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_USE_NUCLEAR_WEAPON',			1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_ALLIANCE',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_ALLIANCE_CULTURAL',			1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_ALLIANCE_ECONOMIC',			1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_ALLIANCE_RESEARCH',			1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_ALLIANCE_MILITARY',			0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_ALLIANCE_RELIGIOUS',			0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Diplo',			'DIPLOACTION_RENEW_ALLIANCE',				1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Ally',			'ALLIANCE_CULTURAL',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Ally',			'ALLIANCE_ECONOMIC',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Ally',			'ALLIANCE_RESEARCH',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Ally',			'ALLIANCE_MILITARY',						0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Ally',			'ALLIANCE_RELIGIOUS',						0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_PlotEv',			'NearestFriendlyCity',						1,			-1,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Strategies',		'VICTORY_STRATEGY_SCIENCE_VICTORY',			1,			-1,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Strategies',		'VICTORY_STRATEGY_DIPLOMATIC_VICTORY',		1,			-1,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Yields',			'YIELD_FOOD',								1,			20,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Yields',			'YIELD_SCIENCE',							1,			8,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_PsYields',		'PSEUDOYIELD_DIPLOMATIC_FAVOR',				1,			50,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_PsYields',		'PSEUDOYIELD_NUCLEAR_WEAPON',				1,			25,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Techs',			'TECH_NUCLEAR_FUSION',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Techs',			'TECH_APPRENTICESHIP',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Civics',			'CIVIC_FEUDALISM',							1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Districts',		'DISTRICT_INDUSTRIAL_ZONE',					1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Buildings',		'BUILDING_FACTORY',							1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Buildings',		'BUILDING_GOV_TALL',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Buildings',		'BUILDING_TEMPLE_ARTEMIS',					1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Buildings',		'BUILDING_COLOSSEUM',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Buildings',		'BUILDING_HANGING_GARDENS',					1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Buildings',		'BUILDING_WALLS',							1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Buildings',		'BUILDING_CASTLE',							1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Buildings',		'BUILDING_STAR_FORT',						1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Units',			'UNIT_SETTLER',								0,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Proj',			'PROJECT_LOSSUS_PROJECT',					1,			0,			NULL),
(	'LEADER_STELLARIS_ELLIS_5_Proj',			'PROJECT_ONE_VOICE_RULES',					1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_OPEN_BORDERS',					0,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_MAKE_PEACE',					0,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DIPLOMATIC_DELEGATION',		0,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_RESIDENT_EMBASSY',				0,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_FRIENDSHIP',			0,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_COLONIAL_WAR',			1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_GOLDEN_AGE_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_IDEOLOGICAL_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_WAR_OF_RETRIBUTION',	1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_THIRD_PARTY_WAR',				1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_FORMAL_WAR',			1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_HOLY_WAR',				1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_LIBERATION_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_PROTECTORATE_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_RECONQUEST_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_SURPRISE_WAR',			0,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_TERRITORIAL_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DECLARE_WAR_MINOR_CIV',		1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_DENOUNCE',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_JOINT_WAR',					1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_USE_NUCLEAR_WEAPON',			1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_ALLIANCE',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_ALLIANCE_CULTURAL',			1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_ALLIANCE_ECONOMIC',			1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_ALLIANCE_RESEARCH',			1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_ALLIANCE_MILITARY',			1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_ALLIANCE_RELIGIOUS',			1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Diplo',			'DIPLOACTION_RENEW_ALLIANCE',				1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Ally',				'ALLIANCE_CULTURAL',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Ally',				'ALLIANCE_ECONOMIC',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Ally',				'ALLIANCE_RESEARCH',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Ally',				'ALLIANCE_MILITARY',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Ally',				'ALLIANCE_RELIGIOUS',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'TotalYield',								1,			5,			'YIELD_FOOD'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'TotalYield',								1,			5,			'YIELD_PRODUCTION'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'SpecificResource',							1,			3,			'RESOURCE_HORSES'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'SpecificResource',							1,			5,			'RESOURCE_IRON'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'SpecificResource',							1,			3,			'RESOURCE_NITER'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'SpecificResource',							1,			6,			'RESOURCE_COAL'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'SpecificResource',							1,			12,			'RESOURCE_OIL'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'SpecificResource',							1,			4,			'RESOURCE_ALUMINUM'),
(	'LEADER_STELLARIS_ZOEY_3_PlotEv',			'SpecificResource',							1,			8,			'RESOURCE_URANIUM'),
(	'LEADER_STELLARIS_ZOEY_3_Strategies',		'VICTORY_STRATEGY_SCIENCE_VICTORY',			1,			-1,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Strategies',		'VICTORY_STRATEGY_MILITARY_VICTORY',		1,			-1,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Yields',			'YIELD_SCIENCE',							1,			5,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Yields',			'YIELD_FAITH',								1,			5,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_PsYields',			'PSEUDOYIELD_GPP_GENERAL',					1,			15,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_PsYields',			'PSEUDOYIELD_GPP_PROPHET',					1,			25,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_PsYields',			'PSEUDOYIELD_HAPPINESS',					1,			10,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_PsYields',			'PSEUDOYIELD_UNIT_COMBAT',					1,			15,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_PsYields',			'PSEUDOYIELD_UNIT_SETTLER',					1,			25,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_PsYields',			'PSEUDOYIELD_NUCLEAR_WEAPON',				1,			25,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Techs',			'TECH_NUCLEAR_FUSION',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Techs',			'TECH_ASTROLOGY',							1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Districts',		'DISTRICT_HOLY_SITE',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Districts',		'DISTRICT_CAMPUS',							1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Buildings',		'BUILDING_SHRINE',							1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Buildings',		'BUILDING_GOV_FAITH',						1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Proj',				'PROJECT_LOSSUS_PROJECT',					1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Proj',				'PROJECT_ONE_VOICE_RULES',					1,			0,			NULL),
(	'LEADER_STELLARIS_ZOEY_3_Proj',				'PROJECT_BECOME_THE_CRISIS',				1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_OPEN_BORDERS',					1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_MAKE_PEACE',					1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DIPLOMATIC_DELEGATION',		1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_RESIDENT_EMBASSY',				1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_FRIENDSHIP',			1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_COLONIAL_WAR',			0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_GOLDEN_AGE_WAR',		0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_IDEOLOGICAL_WAR',		0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_WAR_OF_RETRIBUTION',	0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_THIRD_PARTY_WAR',				0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_FORMAL_WAR',			0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_HOLY_WAR',				0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_LIBERATION_WAR',		0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_PROTECTORATE_WAR',		0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_RECONQUEST_WAR',		1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_SURPRISE_WAR',			0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_TERRITORIAL_WAR',		0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DECLARE_WAR_MINOR_CIV',		0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_DENOUNCE',						0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_JOINT_WAR',					0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_USE_NUCLEAR_WEAPON',			1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_ALLIANCE',						1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_ALLIANCE_CULTURAL',			0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_ALLIANCE_ECONOMIC',			0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_ALLIANCE_RESEARCH',			1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_ALLIANCE_MILITARY',			0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_ALLIANCE_RELIGIOUS',			0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Diplo',				'DIPLOACTION_RENEW_ALLIANCE',				1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Ally',				'ALLIANCE_CULTURAL',						1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Ally',				'ALLIANCE_ECONOMIC',						0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Ally',				'ALLIANCE_RESEARCH',						1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Ally',				'ALLIANCE_MILITARY',						0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Ally',				'ALLIANCE_RELIGIOUS',						0,			0,			NULL),
(	'LEADER_STELLARIS_GREY_PlotEv',				'TotalYield',								1,			6,			'YIELD_FOOD'),
(	'LEADER_STELLARIS_GREY_PlotEv',				'TotalYield',								1,			6,			'YIELD_PRODUCTION'),
(	'LEADER_STELLARIS_GREY_PlotEv',				'SpecificResource',							1,			4,			'RESOURCE_COAL'),
(	'LEADER_STELLARIS_GREY_PlotEv',				'SpecificResource',							1,			12,			'RESOURCE_OIL'),
(	'LEADER_STELLARIS_GREY_PlotEv',				'SpecificResource',							1,			6,			'RESOURCE_ALUMINUM'),
(	'LEADER_STELLARIS_GREY_PlotEv',				'SpecificResource',							1,			8,			'RESOURCE_URANIUM'),
(	'LEADER_STELLARIS_GREY_Strategies',			'VICTORY_STRATEGY_SCIENCE_VICTORY',			1,			-3,			NULL),
(	'LEADER_STELLARIS_GREY_Yields',				'YIELD_SCIENCE',							1,			25,			NULL),
(	'LEADER_STELLARIS_GREY_Yields',				'YIELD_FOOD',								1,			5,			NULL),
(	'LEADER_STELLARIS_GREY_Yields',				'YIELD_PRODUCTION',							1,			5,			NULL),
(	'LEADER_STELLARIS_GREY_PsYields',			'PSEUDOYIELD_GPP_SCIENTIST',				1,			50,			NULL),
(	'LEADER_STELLARIS_GREY_PsYields',			'PSEUDOYIELD_HAPPINESS',					1,			25,			NULL),
(	'LEADER_STELLARIS_GREY_PsYields',			'PSEUDOYIELD_NUCLEAR_WEAPON',				1,			25,			NULL),
(	'LEADER_STELLARIS_GREY_Techs',				'TECH_NUCLEAR_FUSION',						1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Techs',				'TECH_WRITING',								1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Techs',				'TECH_SCIENTIFIC_THEORY',					1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Techs',				'TECH_EDUCATION',							1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Civics',				'CIVIC_RECORDED_HISTORY',					1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Districts',			'DISTRICT_CAMPUS',							1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Buildings',			'BUILDING_LIBRARY',							1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Buildings',			'BUILDING_GREAT_LIBRARY',					1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Buildings',			'BUILDING_OXFORD_UNIVERSITY',				1,			0,			NULL),
(	'LEADER_STELLARIS_GREY_Proj',				'PROJECT_LOSSUS_PROJECT',					1,			0,			NULL);

