INSERT INTO PlayerItems
(	Domain,							CivilizationType,				LeaderType,				Type,					Icon,							Name,								Description,							SortIndex) VALUES
(	'Players:Expansion2_Players',	'CIVILIZATION_HOLLOWNEST',		'LEADER_RADIANCE',		'UNIT_HOLLOW_KNIGHT',	'ICON_UNIT_HOLLOW_KNIGHT',		'LOC_UNIT_HOLLOW_KNIGHT_NAME',		'LOC_UNIT_HOLLOW_KNIGHT_DESCRIPTION',	10),
(	'Players:Expansion2_Players',	'CIVILIZATION_HOLLOWNEST',		'LEADER_GOD_OF_GODS',	'UNIT_HOLLOW_KNIGHT',	'ICON_UNIT_HOLLOW_KNIGHT',		'LOC_UNIT_HOLLOW_KNIGHT_NAME',		'LOC_UNIT_HOLLOW_KNIGHT_DESCRIPTION',	10),
(	'Players:Expansion2_Players',	'CIVILIZATION_HOLLOWNEST',		'LEADER_WANDERER',		'UNIT_HOLLOW_KNIGHT',	'ICON_UNIT_HOLLOW_KNIGHT',		'LOC_UNIT_HOLLOW_KNIGHT_NAME',		'LOC_UNIT_HOLLOW_KNIGHT_DESCRIPTION',	10),
(	'Players:Expansion2_Players',	'CIVILIZATION_HOLLOWNEST',		'LEADER_WYRMS',			'UNIT_HOLLOW_KNIGHT',	'ICON_UNIT_HOLLOW_KNIGHT',		'LOC_UNIT_HOLLOW_KNIGHT_NAME',		'LOC_UNIT_HOLLOW_KNIGHT_DESCRIPTION',	10),
(	'Players:Expansion2_Players',	'CIVILIZATION_HOLLOWNEST',		'LEADER_GRIMM',			'UNIT_HOLLOW_KNIGHT',	'ICON_UNIT_HOLLOW_KNIGHT',		'LOC_UNIT_HOLLOW_KNIGHT_NAME',		'LOC_UNIT_HOLLOW_KNIGHT_DESCRIPTION',	10);

