CodeTemplateGeneratedBy_SQL = '''
-- Template generated by Civ6ModTool-FastCivilizaiton
-- github: https://github.com/Wldcmzy/Civ6ModTool-FastCivilizaiton
------------------------------------------------------------------
'''.strip() + '\n\n'

CodeTemplateGeneratedBy_XML = '''
<!-- Template generated by Civ6ModTool-FastCivilizaiton -->
<!-- github: https://github.com/Wldcmzy/Civ6ModTool-FastCivilizaiton -->
<!-- --------------------------------------------------------------- -->
'''.strip() + '\n\n'

authorSQL = CodeTemplateGeneratedBy_SQL + '''
-- Author: {Author}
-- DateCreated: {DateCreated}
------------------------------------------------------------------
'''.strip() + '\n\n'

authorXML = CodeTemplateGeneratedBy_XML + '''
<!-- Author: {Author} -->
<!-- DateCreated: {DateCreated} -->
<!-- --------------------------------------------------------------- -->
'''.strip() + '\n\n'