
CUSTOM_CIVILIZATION_NAME = '##CUSTOM_CIVILIZATION_NAME##'
CUSTOM_LEADER_NAME = '##CUSTOM_LEADER_NAME##'
CUSTOM_LEADER_CAPITAL_CITY_NAME = '##CUSTOM_LEADER_CAPITAL_CITY_NAME##'

SQL_CIVILIZAITON = '''
INSERT INTO Types
(Type, Kind) VALUES
('##CUSTOM_CIVILIZATION_NAME##', 'KIND_CIVILIZATION'),
('TRAIT_##CUSTOM_CIVILIZATION_NAME##', 'KIND_TRAIT');

INSERT INTO Civilizations
(CivilizationType, Name, Description, Adjective, StartingCivilizationLevelType, RandomCityNameDepth, Ethnicity) VALUES
('##CUSTOM_CIVILIZATION_NAME##', 'LOC_##CUSTOM_CIVILIZATION_NAME##_NAME', 'LOC_##CUSTOM_CIVILIZATION_NAME##_DESCRIPTION', 'LOC_##CUSTOM_CIVILIZATION_NAME##_ADJECTIVE',	 'CIVILIZATION_LEVEL_FULL_CIV',	 10, 'ETHNICITY_MEDIT');

INSERT INTO Traits
(TraitType, Name, Description) VALUES
('TRAIT_##CUSTOM_CIVILIZATION_NAME##', 'LOC_TRAIT_##CUSTOM_CIVILIZATION_NAME##_NAME', 'LOC_TRAIT_##CUSTOM_CIVILIZATION_NAME##_DESCRIPTION');

INSERT INTO CivilizationTraits
(CivilizationType, TraitType) VALUES
('##CUSTOM_CIVILIZATION_NAME##', 'TRAIT_##CUSTOM_CIVILIZATION_NAME##');

'''.strip()


SQL_LEADERS = '''
INSERT INTO Types
(Type,  Kind) VALUES
('##CUSTOM_LEADER_NAME##', 'KIND_LEADER'), 
('TRAIT_##CUSTOM_LEADER_NAME##', 'KIND_TRAIT');

INSERT INTO Traits
(TraitType,  Name,  Description) VALUES
('TRAIT_##CUSTOM_LEADER_NAME##', 'LOC_TRAIT_##CUSTOM_LEADER_NAME##_NAME', 'LOC_TRAIT_##CUSTOM_LEADER_NAME##_DESCRIPTION');

INSERT INTO Leaders
(LeaderType,  Name,  InheritFrom,  SceneLayers) VALUES
('##CUSTOM_LEADER_NAME##', 'LOC_##CUSTOM_LEADER_NAME##_NAME', 'LEADER_DEFAULT', '4');

INSERT INTO LeaderTraits
(LeaderType,  TraitType) VALUES
('##CUSTOM_LEADER_NAME##', 'TRAIT_##CUSTOM_LEADER_NAME##');

INSERT INTO LeaderQuotes
(LeaderType,  Quote) VALUES
('##CUSTOM_LEADER_NAME##', 'LOC_PEDIA_LEADERS_PAGE_##CUSTOM_LEADER_NAME##_QUOTE');

INSERT INTO CivilizationLeaders
(LeaderType, CivilizationType, CapitalName) VALUES 
('##CUSTOM_LEADER_NAME##', '##CUSTOM_CIVILIZATION_NAME##', '##CUSTOM_LEADER_CAPITAL_CITY_NAME##');
'''.strip()


SQL_LEADERS_CONFIG = '''
INSERT INTO Players
(Domain, CivilizationType, LeaderType, CivilizationName, CivilizationIcon, LeaderName, LeaderIcon, CivilizationAbilityName, CivilizationAbilityDescription, CivilizationAbilityIcon, LeaderAbilityName, LeaderAbilityDescription, LeaderAbilityIcon, Portrait, PortraitBackground) VALUES
{Players}
'''.strip()
SQL_LEADERS_CONFIG_PLAYERS = '''
('Players:Expansion2_Players','##CUSTOM_CIVILIZATION_NAME##','##CUSTOM_LEADER_NAME##','LOC_##CUSTOM_CIVILIZATION_NAME##_NAME','ICON_##CUSTOM_CIVILIZATION_NAME##','LOC_##CUSTOM_LEADER_NAME##_NAME','ICON_##CUSTOM_LEADER_NAME##','LOC_TRAIT_##CUSTOM_CIVILIZATION_NAME##_NAME','LOC_TRAIT_##CUSTOM_CIVILIZATION_NAME##_DESCRIPTION','ICON_##CUSTOM_CIVILIZATION_NAME##','LOC_TRAIT_##CUSTOM_LEADER_NAME##_NAME','LOC_TRAIT_##CUSTOM_LEADER_NAME##_DESCRIPTION','ICON_##CUSTOM_LEADER_NAME##',NULL,NULL)
'''.strip()