
CUSTOM_CIVILIZATION_NAME = '##CUSTOM_CIVILIZATION_NAME##'
CUSTOM_LEADER_NAME = '##CUSTOM_LEADER_NAME##'
CUSTOM_LEADER_CAPITAL_CITY_NAME = '##CUSTOM_LEADER_CAPITAL_CITY_NAME##'

SQL_CIVILIZAITON = '''
INSERT INTO Types
(Type, Kind) VALUES
('##CUSTOM_CIVILIZATION_NAME##', 'KIND_CIVILIZATION'),
('TRAIT_##CUSTOM_CIVILIZATION_NAME##', 'KIND_TRAIT');

INSERT INTO Civilizations
(CivilizationType, Name, Description, Adjective, StartingCivilizationLevelType, RandomCityNameDepth, Ethnicity) VALUES
('##CUSTOM_CIVILIZATION_NAME##', 'LOC_##CUSTOM_CIVILIZATION_NAME##_NAME', 'LOC_##CUSTOM_CIVILIZATION_NAME##_DESCRIPTION', 'LOC_##CUSTOM_CIVILIZATION_NAME##_ADJECTIVE',	 'CIVILIZATION_LEVEL_FULL_CIV',	 10, 'ETHNICITY_MEDIT');

INSERT INTO Traits
(TraitType, Name, Description) VALUES
('TRAIT_##CUSTOM_CIVILIZATION_NAME##', 'LOC_TRAIT_##CUSTOM_CIVILIZATION_NAME##_NAME', 'LOC_TRAIT_##CUSTOM_CIVILIZATION_NAME##_DESCRIPTION');

INSERT INTO CivilizationTraits
(CivilizationType, TraitType) VALUES
('##CUSTOM_CIVILIZATION_NAME##', 'TRAIT_##CUSTOM_CIVILIZATION_NAME##');

'''.strip()


SQL_LEADERS = '''
INSERT INTO Types
(Type,  Kind) VALUES
('##CUSTOM_LEADER_NAME##', 'KIND_LEADER'), 
('TRAIT_##CUSTOM_LEADER_NAME##', 'KIND_TRAIT');

INSERT INTO Traits
(TraitType,  Name,  Description) VALUES
('TRAIT_##CUSTOM_LEADER_NAME##', 'LOC_TRAIT_##CUSTOM_LEADER_NAME##_NAME', 'LOC_TRAIT_##CUSTOM_LEADER_NAME##_DESCRIPTION');

INSERT INTO Leaders
(LeaderType,  Name,  InheritFrom,  SceneLayers) VALUES
('##CUSTOM_LEADER_NAME##', 'LOC_##CUSTOM_LEADER_NAME##_NAME', 'LEADER_DEFAULT', '4');

INSERT INTO LeaderTraits
(LeaderType,  TraitType) VALUES
('##CUSTOM_LEADER_NAME##', 'TRAIT_##CUSTOM_LEADER_NAME##');

INSERT INTO LeaderQuotes
(LeaderType,  Quote) VALUES
('##CUSTOM_LEADER_NAME##', 'LOC_PEDIA_LEADERS_PAGE_##CUSTOM_LEADER_NAME##_QUOTE');

INSERT INTO CivilizationLeaders
(LeaderType, CivilizationType, CapitalName) VALUES 
('##CUSTOM_LEADER_NAME##', '##CUSTOM_CIVILIZATION_NAME##', '##CUSTOM_LEADER_CAPITAL_CITY_NAME##');
'''.strip()


SQL_LEADERS_CONFIG = '''
INSERT INTO Players
(Domain, CivilizationType, LeaderType, CivilizationName, CivilizationIcon, LeaderName, LeaderIcon, CivilizationAbilityName, CivilizationAbilityDescription, CivilizationAbilityIcon, LeaderAbilityName, LeaderAbilityDescription, LeaderAbilityIcon, Portrait, PortraitBackground) VALUES
{Players}
'''.strip()
SQL_LEADERS_CONFIG_PLAYERS = '''
('Players:Expansion2_Players','##CUSTOM_CIVILIZATION_NAME##','##CUSTOM_LEADER_NAME##','LOC_##CUSTOM_CIVILIZATION_NAME##_NAME','ICON_##CUSTOM_CIVILIZATION_NAME##','LOC_##CUSTOM_LEADER_NAME##_NAME','ICON_##CUSTOM_LEADER_NAME##','LOC_TRAIT_##CUSTOM_CIVILIZATION_NAME##_NAME','LOC_TRAIT_##CUSTOM_CIVILIZATION_NAME##_DESCRIPTION','ICON_##CUSTOM_CIVILIZATION_NAME##','LOC_TRAIT_##CUSTOM_LEADER_NAME##_NAME','LOC_TRAIT_##CUSTOM_LEADER_NAME##_DESCRIPTION','ICON_##CUSTOM_LEADER_NAME##',NULL,NULL)
'''.strip()

SQL_LEADER_AGENDAS = '''
INSERT INTO Types			
(Type, Kind)VALUES
('TRAIT_AGENDA_##CUSTOM_LEADER_NAME##', 'KIND_TRAIT');

INSERT INTO Traits			
(TraitType, Name, Description)VALUES
('TRAIT_AGENDA_##CUSTOM_LEADER_NAME##', 'LOC_AGENDA_##CUSTOM_LEADER_NAME##_NAME', 'LOC_AGENDA_##CUSTOM_LEADER_NAME##_DESCRIPTION');

INSERT INTO Agendas			
(AgendaType, Name, Description) VALUES
('AGENDA_##CUSTOM_LEADER_NAME##', 'LOC_AGENDA_##CUSTOM_LEADER_NAME##_NAME', 'LOC_AGENDA_##CUSTOM_LEADER_NAME##_DESCRIPTION');

INSERT INTO AgendaTraits			
(AgendaType, TraitType) VALUES
('AGENDA_##CUSTOM_LEADER_NAME##', 'TRAIT_AGENDA_##CUSTOM_LEADER_NAME##');

INSERT INTO HistoricalAgendas	
(LeaderType, AgendaType) VALUES
('##CUSTOM_LEADER_NAME##', 'AGENDA_##CUSTOM_LEADER_NAME##');

--请根据需求修改
INSERT INTO ExclusiveAgendas			
(AgendaOne, AgendaTwo) VALUES
();

--请根据需求修改
INSERT INTO ModifierStrings
(ModifierId,										Context,	Text) VALUES
('MODIFIER_TRAIT_AGENDA_##CUSTOM_LEADER_NAME##_1',	'Sample',	'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL'),
('MODIFIER_TRAIT_AGENDA_##CUSTOM_LEADER_NAME##_2',	'Sample',	'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL');
'''.strip()

SQL_LEADER_AI = '''
-- 本文件仅作参考，请根据需求修改。

INSERT INTO AiListTypes 
(ListType) VALUES	
('##CUSTOM_LEADER_NAME##_Diplo'),
('##CUSTOM_LEADER_NAME##_Ally'),
('##CUSTOM_LEADER_NAME##_PlotEv'),
('##CUSTOM_LEADER_NAME##_Strategies'),
('##CUSTOM_LEADER_NAME##_Yields'),
('##CUSTOM_LEADER_NAME##_PsYields'),
('##CUSTOM_LEADER_NAME##_Techs'),
('##CUSTOM_LEADER_NAME##_Civics'),
('##CUSTOM_LEADER_NAME##_Districts'),
('##CUSTOM_LEADER_NAME##_Buildings'),
('##CUSTOM_LEADER_NAME##_Proj');


INSERT INTO AiLists 
(LeaderType, ListType, System) VALUES
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Diplo',		'DiplomaticActions'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Ally',		'Alliances'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_PlotEv',		'PlotEvaluations'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Strategies',	'Strategies'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Yields',		'Yields'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_PsYields',	'PseudoYields'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Techs',		'Techs'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Civics',		'Civics'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Districts',	'Districts'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Buildings',	'Buildings'),
('TRAIT_##CUSTOM_LEADER_NAME##',		'##CUSTOM_LEADER_NAME##_Proj',		'Projects');


INSERT INTO AiFavoredItems 
(ListType,									Item,									Favored,Value,		StringVal) VALUES
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_OPEN_BORDERS',					1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_MAKE_PEACE',					1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DIPLOMATIC_DELEGATION',		1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_RESIDENT_EMBASSY',				1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_FRIENDSHIP',			1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_COLONIAL_WAR',			0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_GOLDEN_AGE_WAR',		0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_IDEOLOGICAL_WAR',		0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_WAR_OF_RETRIBUTION',	0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_THIRD_PARTY_WAR',				0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_FORMAL_WAR',			0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_HOLY_WAR',				0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_LIBERATION_WAR',		0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_PROTECTORATE_WAR',		0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_RECONQUEST_WAR',		1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_SURPRISE_WAR',			0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_TERRITORIAL_WAR',		0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DECLARE_WAR_MINOR_CIV',		0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_DENOUNCE',						0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_JOINT_WAR',					0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_USE_NUCLEAR_WEAPON',			1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_ALLIANCE',						1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_ALLIANCE_CULTURAL',			0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_ALLIANCE_ECONOMIC',			0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_ALLIANCE_RESEARCH',			1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_ALLIANCE_MILITARY',			0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_ALLIANCE_RELIGIOUS',			0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Diplo',			'DIPLOACTION_RENEW_ALLIANCE',				1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Ally',			'ALLIANCE_CULTURAL',						1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Ally',			'ALLIANCE_ECONOMIC',						0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Ally',			'ALLIANCE_RESEARCH',						1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Ally',			'ALLIANCE_MILITARY',						0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Ally',			'ALLIANCE_RELIGIOUS',						0,		0,	NULL),
('##CUSTOM_LEADER_NAME##_PlotEv',		'Total Yield',								1,		6,			'YIELD_FOOD'),
('##CUSTOM_LEADER_NAME##_PlotEv',		'Total Yield',								1,		6,			'YIELD_PRODUCTION'),
('##CUSTOM_LEADER_NAME##_PlotEv',		'Specific Resource',						1,		4,			'RESOURCE_COAL'),
('##CUSTOM_LEADER_NAME##_PlotEv',		'Specific Resource',						1,		12,			'RESOURCE_OIL'),
('##CUSTOM_LEADER_NAME##_PlotEv',		'Specific Resource',						1,		6,			'RESOURCE_ALUMINUM'),
('##CUSTOM_LEADER_NAME##_PlotEv',		'Specific Resource',						1,		8,			'RESOURCE_URANIUM'),
('##CUSTOM_LEADER_NAME##_Strategies',	'VICTORY_STRATEGY_SCIENCE_VICTORY',			1,		-3,			NULL),
('##CUSTOM_LEADER_NAME##_Yields',		'YIELD_SCIENCE',							1,		25,			NULL),
('##CUSTOM_LEADER_NAME##_Yields',		'YIELD_FOOD',								1,		5,			NULL),
('##CUSTOM_LEADER_NAME##_Yields',		'YIELD_PRODUCTION',							1,		5,			NULL),
('##CUSTOM_LEADER_NAME##_PsYields',		'PSEUDOYIELD_GPP_SCIENTIST',				1,		50,			NULL),
('##CUSTOM_LEADER_NAME##_PsYields',		'PSEUDOYIELD_HAPPINESS',					1,		25,			NULL),
('##CUSTOM_LEADER_NAME##_PsYields',		'PSEUDOYIELD_NUCLEAR_WEAPON',				1,		25,			NULL),
('##CUSTOM_LEADER_NAME##_Techs',			'TECH_NUCLEAR_FUSION',						1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Techs',			'TECH_WRITING',								1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Techs',			'TECH_SCIENTIFIC_THEORY',					1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Techs',			'TECH_EDUCATION',							1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Civics',		'CIVIC_RECORDED_HISTORY',					1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Districts',		'DISTRICT_CAMPUS',							1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Buildings',		'BUILDING_LIBRARY',							1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Buildings',		'BUILDING_GREAT_LIBRARY',					1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Buildings',		'BUILDING_OXFORD_UNIVERSITY',				1,		0,	NULL),
('##CUSTOM_LEADER_NAME##_Proj',			'PROJECT_LOSSUS_PROJECT',					1,		0,	NULL);
'''.strip()